version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/ci

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: iut_notes-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: iut_notes-{{ checksum "pom.xml" }}
      
      - run: mvn install
      
      #- store_test_results:
      #   path: target/surefire-reports
      
      - store_artifacts:
          path: target/WebAPI-1.0-jar-with-dependencies.jar

      - save_cache:
          key: finalJar-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - target/WebAPI-1.0-jar-with-dependencies.jar
  deploy:
    machine:
      enabled: true
    steps:
      - restore_cache:
          keys:
            - finalJar-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy Over SSH
          command: |
            scp -r -p /home/circleci/ci/target/WebAPI-1.0-jar-with-dependencies.jar $SSH_USER@$SSH_HOST:/home/web/Web.jar
            ssh $SSH_USER@$SSH_HOST web reboot

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master