on:
  port: 81
  address: 0.0.0.0

admin:
  port: ${on.port}
  address: ${on.address}

app:
  contextPath: ''
  home: /

gui:
  brand: 'IUT'
  search: false
  navbar: true
  fluid: false
  cdn: auto
  menu: {}

users:
  grj3360a:
    roles: administrator

jdbc:
  driver: com.mysql.jdbc.Driver
  host: sql.ekinoxx.ovh
  url: jdbc:mysql://${jdbc.host}:${jdbc.port}/iut?${jdbc.options}
  username: iut
  password: iut$password
  port: 3306
  options: logger=Slf4JLogger

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect